"""add moment_of_day to glucose_records

Revision ID: 30005893a46c
Revises: fd3f8eda8eea
Create Date: 2026-05-14 11:42:27.936259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30005893a46c'
down_revision: Union[str, Sequence[str], None] = 'fd3f8eda8eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_records', sa.Column('moment_of_day', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glucose_records', 'moment_of_day')
    # ### end Alembic commands ###
