"""add user_id to glucose_records

Revision ID: fd3f8eda8eea
Revises: 427cc3680006
Create Date: 2026-05-13 11:45:36.563109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fd3f8eda8eea"
down_revision: Union[str, Sequence[str], None] = "427cc3680006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("glucose_records", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_glucose_records_user_id_users",
        "glucose_records",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_glucose_records_user_id_users", "glucose_records", type_="foreignkey"
    )
    op.drop_column("glucose_records", "user_id")
    # ### end Alembic commands ###
